package com.cqs.demo.models.unit.strategy.entity;

import java.util.Date;

public class Strategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.id
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.user_id
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private int userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.in_traffic_max
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private Float inTrafficMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.in_traffic_guarantee
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private Float inTrafficGuarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.out_traffic_max
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private Float outTrafficMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.out_traffic_guarantee
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private Float outTrafficGuarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.create_date
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.update_date
     *
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.id
     *
     * @return the value of strategy.id
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.id
     *
     * @param id the value for strategy.id
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.user_id
     *
     * @return the value of strategy.user_id
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public int getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.user_id
     *
     * @param userId the value for strategy.user_id
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.in_traffic_max
     *
     * @return the value of strategy.in_traffic_max
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public float getInTrafficMax() {
        return inTrafficMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.in_traffic_max
     *
     * @param inTrafficMax the value for strategy.in_traffic_max
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setInTrafficMax(float inTrafficMax) {
        this.inTrafficMax = inTrafficMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.in_traffic_guarantee
     *
     * @return the value of strategy.in_traffic_guarantee
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public float getInTrafficGuarantee() {
        return inTrafficGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.in_traffic_guarantee
     *
     * @param inTrafficGuarantee the value for strategy.in_traffic_guarantee
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setInTrafficGuarantee(float inTrafficGuarantee) {
        this.inTrafficGuarantee = inTrafficGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.out_traffic_max
     *
     * @return the value of strategy.out_traffic_max
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public float getOutTrafficMax() {
        return outTrafficMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.out_traffic_max
     *
     * @param outTrafficMax the value for strategy.out_traffic_max
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setOutTrafficMax(float outTrafficMax) {
        this.outTrafficMax = outTrafficMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.out_traffic_guarantee
     *
     * @return the value of strategy.out_traffic_guarantee
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public float getOutTrafficGuarantee() {
        return outTrafficGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.out_traffic_guarantee
     *
     * @param outTrafficGuarantee the value for strategy.out_traffic_guarantee
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setOutTrafficGuarantee(float outTrafficGuarantee) {
        this.outTrafficGuarantee = outTrafficGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.create_date
     *
     * @return the value of strategy.create_date
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.create_date
     *
     * @param createDate the value for strategy.create_date
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.update_date
     *
     * @return the value of strategy.update_date
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.update_date
     *
     * @param updateDate the value for strategy.update_date
     * @mbg.generated Thu Nov 24 21:59:05 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}